#!/usr/bin/env bash
# init-product-repo.sh — Bootstrap my-ai-runtime infrastructure in a product repo.
#
# Usage:
#   bash <runtime>/bootstrap/init-product-repo.sh <product-repo> \
#        [--profiles python,typescript] [--os linux|windows] \
#        [--project-name NAME] [--cbm-project ID] [--install-global] [--no-sync]
#
# Creates .claude/ skeleton, writes runtime.config.yaml (unless present), installs
# the sync wrapper, optionally installs the machine-global discipline layer, then
# runs the initial per-repo sync.
set -euo pipefail

PRODUCT_DIR=""
PROFILES="python"
OS_NAME="linux"
PROJECT_NAME=""
CBM_PROJECT=""
DO_GLOBAL=false
DO_SYNC=true
WITH_AO=false
WITH_SRS=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profiles)     PROFILES="$2"; shift 2 ;;
    --os)           OS_NAME="$2"; shift 2 ;;
    --project-name) PROJECT_NAME="$2"; shift 2 ;;
    --cbm-project)  CBM_PROJECT="$2"; shift 2 ;;
    --install-global) DO_GLOBAL=true; shift ;;
    --with-ao)      WITH_AO=true; shift ;;
    --with-srs)     WITH_AO=true; WITH_SRS=true; shift ;;
    --no-sync)      DO_SYNC=false; shift ;;
    -*)             echo "Unknown flag: $1" >&2; exit 1 ;;
    *)              PRODUCT_DIR="$1"; shift ;;
  esac
done
[[ -n "$PRODUCT_DIR" ]] || { echo "Usage: init-product-repo.sh <product-repo> [--profiles ..] [--os ..]" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
mkdir -p "$PRODUCT_DIR"
PRODUCT_DIR="$(cd "$PRODUCT_DIR" && pwd)"
[[ -n "$PROJECT_NAME" ]] || PROJECT_NAME="$(basename "$PRODUCT_DIR")"

echo "=== Bootstrapping my-ai-runtime ==="
echo "Product : $PRODUCT_DIR"
echo "Runtime : $RUNTIME_DIR"
echo "Profiles: $PROFILES   OS: $OS_NAME   Project: $PROJECT_NAME"
echo ""

# --- .claude/ skeleton ------------------------------------------------------
mkdir -p "$PRODUCT_DIR"/.claude/{agents,skills,quality-gates,rules,templates,references}
echo "Created .claude/ structure"

# --- runtime.config.yaml (seed — don't overwrite) ---------------------------
CFG="$PRODUCT_DIR/runtime.config.yaml"
if [[ -f "$CFG" ]]; then
  echo "runtime.config.yaml exists — left as-is"
else
  # OS-aware defaults
  state_dir="/tmp/claude-workers"
  cbm_bin="~/.local/bin/codebase-memory-mcp"
  [[ "$OS_NAME" == "windows" ]] && { state_dir='%TEMP%\claude-workers'; cbm_bin='%USERPROFILE%\.local\bin\codebase-memory-mcp'; }
  yaml_langs="[$(echo "$PROFILES" | sed 's/,/, /g')]"
  {
    echo "# runtime.config.yaml — generated by init-product-repo.sh"
    echo "# See <runtime>/config/runtime.config.example.yaml for the full schema."
    echo "project_name: $PROJECT_NAME"
    echo "os: $OS_NAME"
    echo "languages: $yaml_langs"
    echo "cbm_project: \"$CBM_PROJECT\""
    echo "cbm_bin: $cbm_bin"
    echo "state_dir: $state_dir"
    if $WITH_AO; then
      echo "capabilities: [ao]"
      echo "# AO story-machinery active — see runtime.config.example.yaml for the ao: block + gate_registry"
    else
      echo "capabilities: []"
    fi
    if $WITH_SRS; then
      echo "srs:"
      echo "  enabled: true"
    fi
  } > "$CFG"
  echo "Wrote runtime.config.yaml$($WITH_AO && echo ' (AO capability enabled)')"
fi

# --- sync wrapper -----------------------------------------------------------
if [[ ! -f "$PRODUCT_DIR/scripts/sync-ai-runtime.sh" ]]; then
  mkdir -p "$PRODUCT_DIR/scripts"
  cat > "$PRODUCT_DIR/scripts/sync-ai-runtime.sh" << 'SYNCEOF'
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRODUCT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
RUNTIME_DIR="${AI_RUNTIME_PATH:-$PRODUCT_DIR/../mgt-ai-runtime}"
if [[ ! -d "$RUNTIME_DIR" ]]; then
  echo "ERROR: AI runtime repo not found at $RUNTIME_DIR (set AI_RUNTIME_PATH)"; exit 1
fi
exec bash "$RUNTIME_DIR/sync/sync-engine.sh" "$RUNTIME_DIR" "$PRODUCT_DIR" "$@"
SYNCEOF
  chmod +x "$PRODUCT_DIR/scripts/sync-ai-runtime.sh"
  echo "Created scripts/sync-ai-runtime.sh"
fi

# --- optional machine-global discipline layer -------------------------------
if $DO_GLOBAL; then
  echo ""
  echo "Installing machine-global discipline layer..."
  bash "$RUNTIME_DIR/global/install-global.sh"
fi

# --- initial per-repo sync --------------------------------------------------
if $DO_SYNC; then
  echo ""
  echo "Running initial sync..."
  bash "$RUNTIME_DIR/sync/sync-engine.sh" "$RUNTIME_DIR" "$PRODUCT_DIR"
fi

echo ""
echo "=== Bootstrap complete ==="
echo "Next steps:"
echo "  1. Review runtime.config.yaml (languages, cbm_project, gates)."
echo "  2. Customize .claude/agents & .claude/skills for your project."
echo "  3. C#/WPF: follow <runtime>/profiles/csharp/adopt.md."
echo "  4. Machine setup (if skipped): bash <runtime>/global/install-global.sh"
echo "  5. Re-sync anytime: bash scripts/sync-ai-runtime.sh --dry-run"
