#!/usr/bin/env bash
# merge-with-rtm-strategy.sh STORY-BRANCH [-- merge-args...]
#
# Wraps `git merge --no-ff` so that conflicts limited to rtm.yaml (srs.rtm_path) are
# resolved automatically: rtm.yaml is auto-generated by rebuild-rtm.sh (never edit
# manually). Two stories in the same wave each touch RTM, so merging the second one
# always conflicts.
#
# OPTIONAL-module gate note (deliberate deviation from the blanket "exit 0 no-op"
# used by the rest of story-machinery/srs/): this script's primary action — the merge
# itself — is needed by the wave/merge orchestration regardless of whether the SRS/RTM
# methodology is in use. No-op'ing the whole script when srs.enabled=false would silently
# skip merges for every product that doesn't opt into SRS, which is worse than the
# feature it's gating. So: the merge always runs; only the RTM-conflict auto-resolve
# FALLBACK below is conditional on srs.enabled (with SRS off there's no rtm.yaml to
# special-case, so any conflict — including on that path — is treated as real and
# escalated like any other).
#
# Strategy:
#   1. `git merge --no-ff <branch>`
#   2. If merge fails AND srs.enabled AND the only conflicted path is rtm.yaml:
#        a. `git checkout --theirs <rtm.yaml>`
#        b. `bash rebuild-rtm.sh`
#        c. `git add <rtm.yaml>`
#        d. `git commit --no-edit`
#   3. If merge fails on any other path (or srs disabled) → bail out (`git merge --abort`),
#      exit 1 with the conflict summary on stdout.
#
# Exit codes: 0 = merge ok (clean or rtm-only auto-resolved); 1 = real conflict
# Output: short JSON `{"status":"clean|rtm-resolved|conflict","details":"..."}`.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../scripts/runtime-config-read.sh"

STORY_BRANCH="${1:?Usage: $0 STORY-BRANCH [-- extra git-merge args]}"
shift || true
EXTRA_ARGS=()
if [[ "${1:-}" == "--" ]]; then
  shift
  EXTRA_ARGS=("$@")
fi

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  printf '{"status":"error","details":"not-a-git-repo"}\n'
  exit 1
}
cd "$REPO_ROOT" || { printf '{"status":"error","details":"cd-repo-root-failed"}\n'; exit 1; }

RTM_REL="$(rcfg srs.rtm_path docs/rtm.yaml)"

emit() {
  local status="$1" details="${2:-}"
  printf '{"status":"%s","details":%s}\n' \
    "$status" \
    "$(printf '%s' "$details" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read().rstrip()))')"
}

MERGE_LOG=$(mktemp)
trap 'rm -f "$MERGE_LOG"' EXIT

if git merge --no-ff --no-edit "${EXTRA_ARGS[@]}" "$STORY_BRANCH" >"$MERGE_LOG" 2>&1; then
  emit "clean" "$(tail -1 "$MERGE_LOG")"
  exit 0
fi

CONFLICTS=$(git diff --name-only --diff-filter=U 2>/dev/null)
if [[ -z "$CONFLICTS" ]]; then
  emit "error" "merge failed but no conflicts: $(tail -3 "$MERGE_LOG" | tr '\n' ';')"
  git merge --abort 2>/dev/null || true
  exit 1
fi

if ! rcfg_bool srs.enabled; then
  emit "conflict" "srs disabled — no rtm auto-resolve strategy; conflicts: $(echo "$CONFLICTS" | tr '\n' ',' | sed 's/,$//')"
  git merge --abort 2>/dev/null || true
  exit 1
fi

# Auto-resolve rtm.yaml-only conflicts.
NON_RTM=$(echo "$CONFLICTS" | grep -vF "$RTM_REL" || true)
if [[ -n "$NON_RTM" ]]; then
  # ВАЖНО (Wave D06+D08+D09 D09 incident): coordinator НЕ должен делать manual
  # `git checkout --theirs <file>` + `git commit --no-edit` после этого abort —
  # это создаёт EMPTY merge commit с потерянными файлами worktree-branch.
  # См. `.claude/skills/run-stories/SKILL.md` → "Merge safety contract".
  git merge --abort 2>/dev/null || true
  CONFLICT_LIST=$(echo "$NON_RTM" | tr '\n' ',' | sed 's/,$//')
  HINT='Coordinator MUST escalate via AskUserQuestion (a) reset+re-merge с manual conflict resolution, (b) cherry-pick range git log <main>..<worktree-branch> --oneline, (c) abort + оставить worktree-branch без интеграции. ЗАПРЕЩЕНО: git checkout --theirs <non-rtm-file> + git commit --no-edit — даёт empty merge commit (D09 data-loss incident).'
  emit "conflict" "non-rtm conflicts: ${CONFLICT_LIST}. ${HINT}"
  exit 1
fi

# rtm-only path. checkout --theirs guarantees we keep the incoming branch's
# generated rtm; rebuild-rtm.sh then re-renders from the now-merged story
# corpus, producing the correct union.
if ! git checkout --theirs "$RTM_REL" 2>>"$MERGE_LOG"; then
  emit "error" "checkout --theirs failed: $(tail -3 "$MERGE_LOG" | tr '\n' ';')"
  git merge --abort 2>/dev/null || true
  exit 1
fi
if ! bash "$SCRIPT_DIR/rebuild-rtm.sh" >>"$MERGE_LOG" 2>&1; then
  emit "error" "rebuild-rtm.sh failed: $(tail -5 "$MERGE_LOG" | tr '\n' ';')"
  git merge --abort 2>/dev/null || true
  exit 1
fi
git add "$RTM_REL"
if ! git commit --no-edit >>"$MERGE_LOG" 2>&1; then
  emit "error" "commit failed: $(tail -3 "$MERGE_LOG" | tr '\n' ';')"
  exit 1
fi
emit "rtm-resolved" "auto-resolved ${RTM_REL} via --theirs + rebuild-rtm.sh"
exit 0
